apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ .Values.name }}
          port: 8000
  {{- if .Values.ingress }}
  {{- if .Values.ingress.tlsSecret }}
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  {{- end }}
